### ISSUE TITLE
Bug!: Cannot read property 'repository' of undefined

### ISSUE THREAD

**Issue by TGTGamer** [skeet70/default-project-board-action#2]
Firstly, I'd like to say thanks for creating a project action which used numbers not URL. I really didn't want to have to write one myself to manage loads of company repositories which have all got the exact same project numbers xD

Unforchantly I'm encountering a issue: 

```
Run skeet70/default-project-board-action@v1
  with:
    github_token: ***
    repository: TGTGamer/virtualfashion
    project: 1
{
  errors: [
    {
      extensions: [Object],
      locations: [Array],
      message: 'Variable $number of type Int! was provided invalid value'
    }
  ]
}
##[error]Cannot read property 'repository' of undefined
```

Please could you advise?

```yml
name: Pull Request Management

# This workflow automatically lables PR to ensure that all PR's are correct within the release draft.

on:
  pull_request:
    types: [ opened, synchronize, reopened, edited ]

jobs:
  assign_project:
    runs-on: ubuntu-latest
    name: Assign to project
    steps:
      - name: Assign NEW pull requests to project DevOps
        uses: skeet70/default-project-board-action@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          repository: ${{ github.repository }}
          issue: ${{ github.event.issue.number }}
          project: 1
```
